In [1]:
import pandas as pd
jeopardy = pd.read_csv('jeopardy.csv')
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams

In [2]:
jeopardy.columns

Index(['Show Number', ' Air Date', ' Round', ' Category', ' Value',
       ' Question', ' Answer'],
      dtype='object')

In [8]:
dict_columns = {}
for c in jeopardy.columns:
    dict_columns[c] = c.strip() 
dict_columns

{' Air Date': 'Air Date',
 ' Answer': 'Answer',
 ' Category': 'Category',
 ' Question': 'Question',
 ' Round': 'Round',
 ' Value': 'Value',
 'Show Number': 'Show Number'}

In [12]:
jeopardy = jeopardy.rename(columns=dict_columns)
jeopardy.columns

Index(['Show Number', 'Air Date', 'Round', 'Category', 'Value', 'Question',
       'Answer'],
      dtype='object')

In [33]:
import re
def normalize_str(value):
    value = value.lower()
    return re.sub("[^A-Za-z0-9\s]", "", value)

jeopardy['clean_question'] = jeopardy['Question'].apply(normalize_str)

In [34]:
jeopardy['clean_answer'] = jeopardy['Answer'].apply(normalize_str)

In [35]:
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200,0.0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200,0.0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200,0.0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200,0.0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200,0.0

In [36]:
def convert_dollor(value):
    if ~pd.isnull(value):
        value = re.sub("[^A-Za-z0-9\s]", "", value)
        try:
            return int(value)
        except ValueError:
            return 0

jeopardy['clean_value'] = jeopardy['Value'].apply(convert_dollor)
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200,0.0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200,0.0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200,0.0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200,0.0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200,0.0

In [37]:
jeopardy['Air Date'] = pd.to_datetime(jeopardy['Air Date'])
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200,0.0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200,0.0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200,0.0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200,0.0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200,0.0

In [38]:
def question_close_to_answer(row):
    split_answer = row['clean_answer'].split(' ')
    split_question = row['clean_question'].split(' ')
    if "the" in split_answer:
        split_answer.remove("the")
    match_count = 0
    if len(split_answer) == 0:
        return 0
    for a in split_answer:
        if a in split_question:
            match_count +=1
    return match_count / len(split_answer)

jeopardy['answer_in_question'] = jeopardy.apply(question_close_to_answer, axis=1)
jeopardy['answer_in_question'].head(5)

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: answer_in_question, dtype: float64

In [39]:
jeopardy['answer_in_question'].mean()

0.060493257069335872

Mean is so low, that is is clear that the finding answer from questions is next to impossible. Thus using this strategy might not be a good way to proceed.

In [42]:
question_overlap = []
terms_used = set()
for i, row in jeopardy.iterrows():
        split_question = row["clean_question"].split(" ")
        split_question = [q for q in split_question if len(q) > 5]
        match_count = 0
        for word in split_question:
            if word in terms_used:
                match_count += 1
        for word in split_question:
            terms_used.add(word)
        if len(split_question) > 0:
            match_count /= len(split_question)
        question_overlap.append(match_count)
jeopardy["question_overlap"] = question_overlap

jeopardy["question_overlap"].mean()

0.69087373156719623

In [43]:
terms_used

{'hrefhttpwwwjarchivecommedia20041231dj25mp3somewhere',
 'andreas',
 'picturesque',
 'embalm',
 'continuous',
 'acclaim',
 'larroquette',
 'pardon',
 'theologian',
 'gaslight',
 'maintained',
 'supersonic',
 'eubanksa',
 'worked',
 'sturgeon',
 'barbara',
 'smalltown',
 'einheriar',
 'esther',
 'eulogized',
 'serialized',
 'dispute',
 'grants',
 'pounds',
 'etchings',
 'inglese',
 'hrefhttpwwwjarchivecommedia19980402dj26jpgherea',
 'banned',
 'schonbein',
 'michigan',
 'famished',
 'orbits',
 'hermosa',
 'effective',
 'pickle',
 'sheldon',
 'mannix',
 'brunette',
 'koprulu',
 'electrician',
 'stress',
 'implant',
 'songwriter',
 'recommended',
 'skopje',
 'hrefhttpwwwjarchivecommedia20080313dj30jpg',
 'empfield',
 'attract',
 'selfreferential',
 'generators',
 'hrefhttpwwwjarchivecommedia20100506j18wmvthesea',
 'oneswhens',
 'realizes',
 'installer',
 'symbolic',
 'hrefhttpwwwjarchivecommedia20061102j13ajpg',
 'cruella',
 'scholar',
 'furlongs',
 'perform',
 'divide',
 'spinoff',
 'perfect',
 'kathleen',
 'gehrig',
 'therapy',
 'rallies',
 'pomegranates',
 'ambushed',
 'galliano',
 'targetblankmaska',
 'monkeyfaced',
 'roofed',
 'millie',
 'hrefhttpwwwjarchivecommedia20090930j10wmvthisa',
 'september',
 'confederation',
 'teacup',
 'lusaka',
 'windpipe',
 'wouldnt',
 'hrefhttpwwwjarchivecommedia20090525j26wmvjimmy',
 'tuptim',
 'mountbattens',
 'ridgenosed',
 'russians',
 'katrina',
 'stalin',
 'senators',
 'sharona',
 'foxglove',
 'treatise',
 'roommate',
 'knowledge',
 'raised',
 'discourteously',
 '16letter',
 'pompous',
 'unspotted',
 'nohitter',
 'daughters',
 'cruces',
 'antoine',
 'jellyfish',
 'embedded',
 'history',
 'mcclain',
 'suited',
 'fairys',
 'fraction',
 'fathoms',
 'hrefhttpwwwjarchivecommedia20110713j07ajpg',
 'champions',
 'cemetery',
 'emmanuel',
 'gomateshwara',
 'balalaika',
 'crucifixion',
 'vulpine',
 'percent',
 'technique',
 'pretzels',
 'thumbsucking',
 'mumtaz',
 'drachmas',
 'galapagos',
 'thermoplastic',
 'captivitiy',
 'lending',
 'archduke',
 'alpaca',
 'harpsichord',
 'dominican',
 'buttermaker',
 'picnic',
 'rdawant',
 'cosmetic',
 'endorsement',
 'cohorts',
 'achieved',
 'hitmaker',
 'shapka',
 'kosher',
 'shocked',
 'furbearer',
 'sparkly',
 'mallowan',
 'complicated',
 'ambrose',
 'exists',
 'popmart',
 'combat',
 'bruegel',
 'purely',
 'campusa',
 'peloponnesus',
 'ribbon',
 '011331',
 'cystic',
 'sadism',
 'hrefhttpwwwjarchivecommedia20091208dj19jpg',
 'choirboy',
 'csonkaa',
 'deglet',
 'advertisement',
 'specter',
 'jeanjacques',
 'carassos',
 '20002001',
 'thermometer',
 'unique',
 'yasmina',
 'kermit',
 'housekeeper',
 'candide',
 'tepidarium',
 'dvoraks',
 'societal',
 'entertainment',
 'eaglesa',
 'dramatist',
 'cruelty',
 'kanaga',
 'hrefhttpwwwjarchivecommedia20091117dj27jpg',
 'lubricants',
 'oftfired',
 'ragged',
 'sumter',
 'movable',
 'beneficiary',
 'brandi',
 'objecto',
 'americana',
 'ocotillo',
 'czechborn',
 'federated',
 'gamete',
 'rodere',
 'finacees',
 'timbers',
 'hrefhttpwwwjarchivecommedia20070724j16jpg',
 'swindler',
 'antebellum',
 'cagney',
 'suspend',
 'sultans',
 'recounted',
 'othello',
 'shooter',
 'mckinley',
 'daymond',
 'compounds',
 'weyden',
 'hrefhttpwwwjarchivecommedia20060406dj28jpg',
 'selleck',
 'halibut',
 'circulation',
 'valley',
 'whiskey',
 'mouthy',
 'steelproducing',
 'linseed',
 'hrefhttpwwwjarchivecommedia20071211j08jpg',
 'hrefhttpwwwjarchivecommedia20090525dj28jpg',
 'hrefhttpwwwjarchivecommedia20040707j13jpg',
 'residue',
 'allergy',
 'crimefighting',
 'hematite',
 'bladder',
 'versailles',
 'wholly',
 'apparel',
 'shrivel',
 'gearbox',
 'veterinarians',
 'tahiti',
 'penning',
 'bertram',
 'goldbergs',
 'yummies',
 'claras',
 'chance',
 'community',
 'beaded',
 'rivers',
 'ministry',
 'practices',
 'hrefhttpwwwjarchivecommedia20080508j21mp3isampleia',
 'arthropod',
 'lunches',
 'working',
 'competitor',
 'nightmaremtvs',
 'benevolent',
 'astrologists',
 'pivotal',
 'whaleheaded',
 'coanchored',
 'goldblatt',
 'heraldic',
 '17661768',
 'whiskies',
 'systematically',
 'container',
 'captives',
 'illfated',
 'pillow',
 'hrefhttpwwwjarchivecommedia20050411j27jpg',
 'obvious',
 'arabic',
 'sciences',
 'roquefort',
 'resources',
 'botany',
 'valparaiso',
 'trolley',
 'extract',
 'herbal',
 'oneraw',
 'ladder',
 'pianistcomposer',
 'mcvicker',
 'grammatically',
 'conscience',
 'curved',
 'chapel',
 'advantage',
 'marmosets',
 'bogart',
 'participating',
 'appears',
 'cremated',
 'ophelia',
 'stauffenberg',
 'constitutional',
 'adults',
 'plains',
 'marabar',
 'utilitarianism',
 'exercising',
 'swedens',
 'coneygarths',
 'specimensa',
 'authors',
 'aagood',
 'classifying',
 'deighton',
 'eurocar',
 'dumitru',
 'oncoming',
 'razorsharp',
 'followinga',
 'insure',
 'functionary',
 'lawrys',
 'overseers',
 'democratic',
 'shelled',
 'caution',
 'shouted',
 'volunteer',
 'horseshoeshaped',
 'targetblanksofia',
 'sapiens',
 'products',
 'introduced',
 'kanagawa',
 'spiraled',
 'postcommunist',
 'tattoo',
 'hehheh',
 'direct',
 'flowery',
 'swingle',
 'solvent',
 'josephs',
 'clinics',
 'tossing',
 'aligns',
 'roethke',
 'training',
 'scopes',
 'online',
 'wayside',
 'arranging',
 'defenseman',
 'valfierno',
 'hrefhttpwwwjarchivecommedia20060329j30jpg',
 'approve',
 'wyndham',
 'mid18th',
 'hrefhttpwwwjarchivecommedia20090204dj08wmvkelly',
 'potassium',
 'leaguers',
 'friedland',
 'offering',
 'isaiah',
 'hrefhttpwwwjarchivecommedia20061012dj28ajpg',
 'targetblankthat',
 'widowed',
 'metasearch',
 'yearling',
 'cleary',
 'hrefhttpwwwjarchivecommedia20081208dj28jpg',
 'parable',
 'hrefhttpwwwjarchivecommedia20001003dj05bjpg',
 'jainism',
 'leaking',
 'eylashes',
 'partout',
 'skating',
 'addition',
 'flooding',
 'omnimedia',
 'unimportant',
 'enrico',
 'capers',
 'baklava',
 'emmett',
 'ruccolo',
 'verasun',
 'poinsett',
 'steeler',
 'kenneth',
 'legitimate',
 'shriners',
 'marvin',
 'littlefoot',
 'inevitable',
 'crisium',
 'elaborate',
 'prepared',
 'sumerians',
 'cappella',
 'sursson',
 'yields',
 'lesser',
 'sacramento',
 'lafitte',
 'hrefhttpwwwjarchivecommedia20090203j24jpg',
 'boomers',
 'checkerboard',
 'austern',
 'impervious',
 'lieder',
 'nadezhda',
 'pritchett',
 'retention',
 'probing',
 'spouse',
 '32millionyearold',
 'eggshell',
 'hrefhttpwwwjarchivecommedia20100621j06wmvalex',
 'gogols',
 'intensified',
 'entirely',
 'eruptions',
 'malpractice',
 'amundsen',
 'notebook',
 'keukenhof',
 'corndogs',
 'wisconsinmadisona',
 'renouncing',
 'soonyi',
 'neutering',
 'slower',
 'hrefhttpwwwjarchivecommedia20090327dj28jpg',
 'domgasse',
 'repatrioted',
 'jubilee',
 'japanese',
 '22yearold',
 'bharat',
 'nicely',
 'flights',
 'extraction',
 'aquino',
 'finally',
 'welded',
 'stamford',
 'general',
 'mesabi',
 'appearing',
 'system',
 'mauler',
 'electronic',
 'entertainerturnedcongressman',
 'inational',
 'banting',
 'skylight',
 'hamilton',
 'whitehall',
 'enhancer',
 'duties',
 'sargent',
 'charities',
 'renfro',
 'cruisin',
 '500000member',
 'albanians',
 'cricket',
 'crashed',
 'someone',
 'plantbreeding',
 'hephaestus',
 'hrefhttpwwwjarchivecommedia20111202j11jpg',
 'cabinetmaker',
 'shapeless',
 'tuchman',
 'exceeding',
 'collar',
 'producing',
 'krakauer',
 'crouse',
 'snaefells',
 'nakajima',
 'sickness',
 'keaton',
 'adding',
 'enjoyment',
 'rockabilly',
 'vegetation',
 'umberto',
 'bremsstrahlung',
 'bowtieclad',
 'jerseyborn',
 'blanket',
 'akiapolaau',
 'crusading',
 'tartini',
 'salvation',
 'palaua',
 'tendons',
 'stoppard',
 'waterways',
 'hrefhttpwwwjarchivecommedia19980320j17mp3herea',
 'requested',
 'toadstool',
 'cosmology',
 'scarlett',
 'caddie',
 'guitar',
 'season',
 'picchua',
 'visigoths',
 'brewed',
 'hrefhttpwwwjarchivecommedia20081208dj25jpg',
 'postpone',
 'giving',
 'hrefhttpwwwjarchivecommedia20080310dj14jpg',
 'lowood',
 'leatherstocking',
 'sartos',
 'libidinous',
 '520foot',
 'bribery',
 'giuseppina',
 'giuliani',
 'tijuana',
 'haptic',
 'starching',
 'subject',
 '150yearold',
 'clique',
 'examination',
 'larson',
 'notched',
 'weddell',
 'hearty',
 'onebyone',
 'trillion',
 'alexakis',
 'surrey',
 'vocabulary',
 'deltoid',
 'separation',
 'jeopardy',
 'turcotte',
 'judson',
 'teletubby',
 'manual',
 'hardware',
 'trivialize',
 'gomera',
 'knowles',
 'segels',
 'gyatso',
 'telephone',
 'medications',
 'hrefhttpwwwjarchivecommedia20050531dj02jpg',
 'worldcom',
 'colcannon',
 'quarantine',
 'pleasing',
 'musicsharing',
 'awarded',
 'enjoys',
 'extraterrestrial',
 'distinctly',
 'reared',
 'propulsion',
 'barnard',
 'mid1950s',
 'fagins',
 'anointing',
 'hexahedron',
 'parasite',
 'marcel',
 'hecate',
 'isreala',
 'kennel',
 'fergusons',
 'bewster',
 'targetblankmurala',
 'nancys',
 'reformation',
 'setter',
 'brasilia',
 'hrefhttpwwwjarchivecommedia20060516dj30wmviyour',
 'wheeler',
 'rastafarian',
 'somebodys',
 'cucumber',
 'honorary',
 'dragged',
 'doubts',
 'sorbet',
 'eligius',
 'solzhenitsyn',
 'gentle',
 'hrefhttpwwwjarchivecommedia20070112dj20ajpg',
 'athenian',
 'schullers',
 'lullaby',
 'hrefhttpwwwjarchivecommedia20010718j14jpg',
 'targetblankpiecesa',
 'vulnerable',
 'cyclists',
 'cappelletto',
 'hrefhttpwwwjarchivecommedia20090211dj12bjpg',
 'megadoses',
 'hrefhttpwwwjarchivecommedia20091117dj05jpg',
 'voyager',
 'hrefhttpwwwjarchivecommedia20100421dj24jpg',
 'netherworld',
 'azimuth',
 'sexsymbol',
 'fairest',
 'passion',
 'fresno',
 'decomposed',
 'silence',
 'coughing',
 'simultaneous',
 'support',
 'borzoi',
 'hrefhttpwwwjarchivecommedia20071115j25jpg',
 'trends',
 'embalming',
 'ceased',
 'uplift',
 'deeper',
 'maniac',
 'rushmore',
 'fainted',
 'settler',
 'johannesburg',
 'durable',
 'champagne',
 'insurance',
 'embolectomy',
 'wister',
 'crimean',
 'folklore',
 'expectations',
 'idealistic',
 'thrashed',
 'murals',
 'helter',
 'debuted',
 'fledgling',
 'corridors',
 'holland',
 'passionate',
 'peyton',
 'flavored',
 'sophie',
 'mcmurtry',
 'hyphens',
 'opportunity',
 '3stage',
 'workbook',
 'integrated',
 'excluded',
 'purify',
 'tecumseh',
 'ransomed',
 'britannica',
 'exhaustive',
 'potiphars',
 'swatted',
 'troposphere',
 'hrefhttpwwwjarchivecommedia20090211j28wmvthisa',
 'proteins',
 'delivery',
 'museums',
 'cityfounding',
 'pianosa',
 'pallino',
 'sparta',
 'brutality',
 '20yearold',
 'retractile',
 'wyomings',
 'buyers',
 'patronage',
 'cougar',
 'cogwheel',
 'buried',
 'regaining',
 'sheriff',
 '400meter',
 'affiliation',
 'between',
 'hrefhttpwwwjarchivecommedia20111103j02jpg',
 'violinhe',
 'cauldron',
 'perfume',
 'luggagebased',
 'vanessa',
 'beheld',
 'funnyman',
 'amleto',
 'confession',
 'shakira',
 'allied',
 'cattrall',
 'heaven',
 'crooners',
 'bantam',
 'mcclellans',
 'sliced',
 'steamboat',
 'dominion',
 'mysterysolving',
 'gezira',
 'searched',
 'reporter',
 'marinade',
 'values',
 'targetblankeastern',
 'change',
 'baptized',
 'argonauts',
 'bibles',
 'marianas',
 'likely',
 'viking',
 'menken',
 'ipanema',
 'acasta',
 'sister',
 'manifested',
 'shakkar',
 'bactine',
 'telescope',
 'timing',
 'giorgios',
 'concert',
 'torontos',
 'wreaths',
 'bestowed',
 'hrefhttpwwwjarchivecommedia20091014j07jpg',
 'rhinemaiden',
 'compson',
 'juvenile',
 'intention',
 'lamarche',
 'cookie',
 'hrefhttpwwwjarchivecommedia20071203dj22mp3slapping',
 'almanack',
 'eisenach',
 'kassebaum',
 'french',
 'branagh',
 'lyreshaped',
 'heavenly',
 'effortordinary',
 'stitches',
 '16button',
 'supercontinent',
 'untruea',
 'spearlike',
 'hrefhttpwwwjarchivecommedia20071226dj30wmvjon',
 'indochinese',
 'yardbirds',
 'jamaica',
 'steves',
 'apogee',
 'intercity',
 'theodor',
 'player',
 'shipwrecked',
 'prisioner',
 'yorkvermont',
 'libyas',
 'jessie',
 'grindavik',
 'godlike',
 'coelenteron',
 'villager',
 'shelby',
 'cadets',
 'ediths',
 'kimono',
 'positions',
 'trotsky',
 'gatsby',
 'meegeren',
 'railways',
 'agenda',
 'relive',
 'melita',
 'solero',
 'smashes',
 'closing',
 'smetana',
 'cantankerous',
 'counters',
 'limpio',
 'pitney',
 'monarch',
 'strips',
 'paralleled',
 'zbigniew',
 'transamerica',
 'bostonbased',
 'fooling',
 'monogamy',
 'moussaka',
 'electing',
 'pussycat',
 'bitesized',
 'prominently',
 'agatha',
 'equatorial',
 'sunshine',
 'heartlight',
 'newborn',
 'sweetheart',
 'hellcats',
 'hrefhttpwwwjarchivecommedia20071106dj23jpg',
 'eveready',
 'investment',
 'windows',
 'baptism',
 'revealing',
 'legions',
 'troupe',
 'transmitter',
 'deckard',
 'complaint',
 'perlmans',
 'advertises',
 'chamberlain',
 'kazantzakis',
 'bengurion',
 'proverbs',
 'borglum',
 'visitor',
 'titania',
 'hrefhttpwwwjarchivecommedia20050307dj26jpg',
 'affirmative',
 'isosceles',
 'saranac',
 'kangaroos',
 'hrefhttpwwwjarchivecommedia20101011dj16jpg',
 'anytime',
 'blossoms',
 'janitor',
 'montanaa',
 'veloso',
 'davison',
 'hispaniola',
 'enlightened',
 'boyhood',
 'mirror',
 'condiment',
 'congressional',
 'navarone',
 'netlike',
 'thants',
 'chopped',
 'meltdown',
 'uninhabited',
 'memorable',
 'homage',
 'intent',
 'embarrassed',
 'rimini',
 'returns',
 'targetblankin',
 'freeing',
 'georgetown',
 'unemployment',
 'rousseau',
 'pigeon',
 'thespian',
 'mariel',
 'laundry',
 'ningbo',
 'macchios',
 'shaves',
 'severe',
 'clothed',
 'mcgraw',
 'portrayer',
 'overlord',
 'corollas',
 'saltier',
 'baseline',
 'drycured',
 'englanders',
 'hrefhttpwwwjarchivecommedia20080408j10jpg',
 'birthstone',
 'international',
 'olenska',
 'topless',
 'supremacy',
 'voters',
 'crewman',
 'skinny',
 'spunky',
 'strikingly',
 'bettor',
 'hrefhttpwwwjarchivecommedia20060426j24jpg',
 'comoros',
 'cambridges',
 'hoffmann',
 'alternaband',
 'zwoarer',
 'overtook',
 'energies',
 'burnham',
 'unfair',
 'smiles',
 'morgan',
 'agincourt',
 'attending',
 'cessation',
 'shertogengosch',
 'belmont',
 'mysterious',
 'dinarzade',
 'unresisting',
 'braised',
 'ironworking',
 'moisture',
 'rodolfo',
 'lighters',
 'kristen',
 'hrefhttpwwwjarchivecommedia20090504dj30wmvthesea',
 'protest',
 'skidmore',
 'trapper',
 'organized',
 'phoenix',
 'pitching',
 'wrinkle',
 'paradise',
 'rendition',
 'upriver',
 'methode',
 'hrefhttpwwwjarchivecommedia20080408dj19jpg',
 'medium',
 'informant',
 'chinesehawaiian',
 'leeroy',
 'necessary',
 'cataleptic',
 'curtis',
 'weatherman',
 'aceydeucy',
 'starledger',
 'decide',
 'serenading',
 'deprivation',
 'descartes',
 'dispensing',
 'guillotined',
 'concentrates',
 'oncepopular',
 'aztecs',
 'before',
 'trochilidae',
 'jawless',
 'ironclad',
 'chinese',
 'cocker',
 'utilized',
 'tonywinning',
 'bitches',
 'queens',
 'stratus',
 'fisher',
 'bionic',
 'methods',
 'spelled',
 'proved',
 'aureum',
 'pointed',
 'highfrequency',
 'concord',
 'caspar',
 'wilsons',
 'jeanluc',
 'chosen',
 'lorraine',
 'lefevre',
 'offshoot',
 'ranger',
 'wunnerful',
 'pleated',
 'mosaic',
 'calculators',
 'hrefhttpwwwjarchivecommedia20071113j14jpg',
 '26year',
 'targetblankkelly',
 'hammerstein',
 'denied',
 'illustration',
 'mooney',
 'counts',
 'quartets',
 'kirriemuir',
 'groundfloor',
 'worthy',
 'hrefhttpwwwjarchivecommedia20050411j30jpg',
 ...}

In [40]:
def low_high(row):
    if row['clean_value'] > 800:
        return 1
    else:
        return 0

jeopardy['high_value'] = jeopardy.apply(low_high, axis=1)
jeopardy.head()

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value,answer_in_question,high_value
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200,0.0,0
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200,0.0,0
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200,0.0,0
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200,0.0,0
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200,0.0,0

In [45]:
def assign_words(word):
    low_count = 0 
    high_count = 0
    for i, r in jeopardy.iterrows():
        if word in r['clean_question'].split(' '):
            if r['high_value'] == 1:
                high_count += 1
            else:
                low_count += 1
    return high_count, low_count

observed_expected = []
comparison_terms = list(terms_used)[0:5]

for t in comparison_terms:
    observed_expected.append(assign_words(t))

In [46]:
observed_expected

[(1, 0), (0, 3), (0, 1), (0, 1), (1, 1)]

In [47]:
high_value_count = jeopardy[jeopardy['high_value'] == 1].shape[0]
low_value_count = jeopardy[jeopardy['high_value'] == 0].shape[0]

chi_squared = []
total = 0
for o,e in observed_expected:
    total += o
    total += e
total

8

In [48]:
total_prop = total/jeopardy.shape[0]
expected_high_value = total_prop * high_value_count
expected_low_value = total_prop * low_value_count

In [ ]:
from scipy.stats import chisquare
import numpa
chisq, p_value = chisquare(observed, expected)